### PR TITLE
Optimization updates

### PR DESCRIPTION
**Pull request by MaxGhenis**
* Change `optimize` to return a tuple of the `OptimizeResult` along with a pandas Series with optimal results. The `OptimizeResult` is the raw `differential_evolution` result, while the Series includes the calculated adult amount as well as the shifted geo supplements.
* Sets the last geo (`NORTHERN_IRELAND`) as a default with zero, to ensure a unique solution
* Shifts negative geo supplements to the child/adult/senior, though this doesn't seem to be working for reform_1
* Add `path` arg to `optimize` to be able to point to a path with FRS files
* Add `opt` function to notebook which applies the same settings to each of the three `optimization` calls
* Adds the appropriate packages to a conda environment (though this doesn't work for me, I had to do it through pip due to deps)
* Change module paths to reflect the current location of the notebook, which is within `uk`; also added `__init__.py`
* Comments, docstrings, style

This is currently producing an error @nikhilwoodruff encountered before though, where disability supplements are apparently not being considered in the cost. See reform 1 and 2 results, where the child/adult/senior amounts are identical, but disability supplements are nonzero. @nikhilwoodruff did you do anything to fix this?
image
image

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
@MaxGhenis thanks, not really sure about the disability costing issue. Though I think [this line](https://github.com/UBICenter/uk/blob/b7b3d26f51ff1d32e8470c69778a12cc6d52c893/py/calc_ubi.py#L267) might be a bug: if we're calculating the total UBI given to households, we should only multiply by the household weight. After removing it I'm getting back-to-normal results, and the disability supplements are slightly different. Interestingly they get a bit more substantial once you take the geo supplements into account, I guess intuitively the geo supplements put a lot more disabled people into the net loser group than, and the supplements increase to keep their winner status?

**Comment by nikhilwoodruff** [comment]
Ok, I finally understand my own code; I added that line (* by household population) to account for geo supplements being given to all people, but I should've put it in the geo calculation segment rather than the whole summation, which compounded with the individual age-based UBI. I've fixed it (not quite sure why it wasn't throwing up bigger bugs before, maybe we had different versions), and re-ran the notebook to get some better numbers.

**Comment by MaxGhenis** [comment]
Re-running with `frs` sorted out and lowering tolerance to 1/10th the normal value (removing `maxiter`) produces results that I think I finally believe! You can see them in [`optimal_params.csv`](https://github.com/UBICenter/uk/pull/22/files#diff-0fcd468d1f9487faed48b42665c5280018d2e0d9e7b732503f28f6d36e70cd32). Basically, 201-206 senior / 117-124 adult / 72-26 child, with disability supplements of ~40 for basic and <5 for severe and enhanced. The highest geo supplement is 9 in North East. Each policy now also gets better in terms of optimization function, which wasn't the case before and is now asserted.

It now takes about 20 minutes to run. The reforms take 10, 15, and 51 iterations, respectively.

I'm going to run it again raising the disability range from 40 to 60, since it seems to be bumping up to just about 40. I'll also add @nikhilwoodruff's notebook, and have it pull in the values from `optimal_params.csv`, unrounded to first check the budget works out, and then rounded to the nearest pound for all the analysis.

**Comment by MaxGhenis** [comment]
Final (I think) run, after raising the disability bounds to 200 and shrinking the tolerance further to 0.0001. Took about 35 minutes.

The general story IMO is: Roughly 125/adult, 205/senior, 75/child is optimal with the simplest model, and shifting 5/adult to fund 100 per person with disability helps too (optimal severe and enhanced bonuses were zero, or maybe negative but we didn't test that). Taking 5 off the base levels to fund small regional supplements helps a tiny bit too. This all comes across as really sensible to me, so I think we can move on to analysis (knowing we tested over 35,000 UBI plans!) if you two agree.

|Reform|Adult|Senior|Child|Disability|Regions|Avg % loss|Iterations|Population|
|-|-|-|-|-|-|-|-|-|
|Base|124|205|76|0|0|5.193%|14|3,861|
|Base + disability|119|205|77|99|0|4.963%|33|8,706|
|Base + disability + region|115|202|72|101|0-8|4.956%|93|24,006|

Going to merge this to avoid another long PR. @nikhilwoodruff I didn't get to adding your notebook but I can do that tomorrow pulling from the csv, or if you'd like you can go ahead.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff per our chat could you post here whether you get the same results when running the notebook from your computer?

**Pull request merged**
