### PR TITLE
Update analysis notebook

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Updated analysis notebook with hopefully final results. Probably needs to be merged after #27 .

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you add `jb/_build` to `.gitignore` and remove those files from the PR?

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Actually forgot this is pre-built, given that, do we actually need the `_build` files?

**Comment by MaxGhenis** [comment]
Also could you flip the spectrum chart so the positive is on the left? This aligns with the [original](https://www.urban.org/urban-wire/how-we-can-better-visualize-analysis-tax-reform-legislation) it was adapted from and I think highlights the benefits of the policy more.
image

Could also be nice to somehow pull out specific numbers from it, e.g. x% benefit by 5% or more (or even just x% benefit). But not sure how that'd work, maybe it belongs in a table instead.

**Comment by nikhilwoodruff** [comment]
> Actually forgot this is pre-built, given that, do we actually need the `_build` files?

I don't think we do, the Jupyter-Book is not actually pre-build, rather the notebooks are pre-executed.

**Pull request merged**
